apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: consumer-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: kube-consumer
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
