apiVersion: v1
kind: Service
metadata:
  name: consumer-svc
  labels:
    app: kube-consumer
spec:
  type: ClusterIP
  selector:
    app: kube-consumer
  ports:
    - port: 80
      targetPort: 8001
      protocol: TCP
      name: http
