apiVersion: v1
kind: Service
metadata:
  name: producer-svc
  labels:
    app: kube-producer
spec:
  type: ClusterIP
  selector:
    app: kube-producer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
