name: CI/CD

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      OWNER: ${{ github.actor }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU (for cross-platform, optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push producer image
        run: |
          docker build -t ${REGISTRY}/${{ github.actor }}/producer:latest ./producer
          docker push ${REGISTRY}/${{ github.actor }}/producer:latest

      - name: Build and push consumer image
        run: |
          docker build -t ${REGISTRY}/${{ github.actor }}/consumer:latest ./consumer
          docker push ${REGISTRY}/${{ github.actor }}/consumer:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: ${{ false }} 
    steps:
      - name: Deploy skipped
        run: echo "Deploy job is skipped"
